// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHY8k6QFwbSUlnkSQNzmjZP0C0YWnn5BY',
    appId: '1:338672992362:web:5c8b92ef560be20c4dca13',
    messagingSenderId: '338672992362',
    projectId: 'to-do-list-firebase-flutter',
    authDomain: 'to-do-list-firebase-flutter.firebaseapp.com',
    storageBucket: 'to-do-list-firebase-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp10yQtciah4ZPpMtJdTENWJS5bjWlt20',
    appId: '1:338672992362:android:ad4bd4ca31a4ecb14dca13',
    messagingSenderId: '338672992362',
    projectId: 'to-do-list-firebase-flutter',
    storageBucket: 'to-do-list-firebase-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDheuV-WGzFu2zKCqEKEYAySsLaNtcmvFA',
    appId: '1:338672992362:ios:2f8e37673883eeca4dca13',
    messagingSenderId: '338672992362',
    projectId: 'to-do-list-firebase-flutter',
    storageBucket: 'to-do-list-firebase-flutter.appspot.com',
    iosClientId: '338672992362-jgkoodvd2kea5chm3dd4bp9iqivn03um.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListFirebase',
  );
}
